### ISSUE TITLE
C1110 bins did not work for me

### ISSUE THREAD

**Issue by gekkoman** [meyerd/xeroxpatrone#5]
Bought a years supply of cheap toner replacements for a FujiXerox C1110 and they had stuffed up EEPROM's fitted completely (blank or incorrect)

I still had some unused working toners and did some dumps so here they are:

  http://www.illimitable.com/fuji.c1110.tar.gz

I'm using buspirate and some python scripts to do the read/write from the chips.

By the way I chopped apart a sata cable to make a connector - right pitch and once you hack into the casing all the pins are exposed so you can correct for the the common ground pins. 

![connector](https://cloud.githubusercontent.com/assets/1953356/8178520/12bdf77c-1452-11e5-9680-943b16f51a43.png)

**Comment by meyerd** [comment]
Thanks! Added to the list.
